#!/usr/bin/env bash
# vidmod 43

VERSION='2.1.0'

[ -n "${VIDMOD_LIB:-}" ] || VIDMOD_LIB="$(dirname "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)")/lib/vidmod.sh"

# shellcheck source=../lib/vidmod.sh
. "$VIDMOD_LIB"

_43_start() {
	vidmod_legacy_start 43 "$@"
}

vidmod_plugin_run "$@"
