TOOL = imgmod
LIBEXEC_BINARIES = imgmod
LIBEXEC_FILES = imgmod lib plugins templates
MANPAGES = $(wildcard man/*.1)
BASH_COMPLETIONS = completions/bash/imgmod
ZSH_COMPLETIONS = completions/zsh/_imgmod
FISH_COMPLETIONS = completions/fish/imgmod.fish

include ../lib/install.mk
