[package]
name = "litesite"
version = "2.0.0"
edition = "2021"
license = "ISC"

[dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["ws"] }
brotli = "8"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
colog = "1.4"
dotenvy = "0.15"
env_logger = "0.11"
flate2 = "1"
futures = "0.3"
log = "0.4"
mime_guess = "2"
minify-html = "0.18"
notify = "8"
notify-debouncer-full = "0.7"
regex = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
walkdir = "2"
zstd = "0.13"
