.TH OSC52PASTE 1 "August 2026" "osc52paste 0.1.0"
.SH NAME
osc52paste \- paste text using OSC 52
.SH SYNOPSIS
.B osc52paste
.SH DESCRIPTION
.B osc52paste
queries the terminal clipboard with OSC 52 and writes its contents to standard
output.
It is equivalent to
.BR "osc52 paste" .
.SH OPTIONS
.TP
.BR -h , " --help"
Show usage information.
.TP
.BR -v , " --version"
Show the version number.
