.TH VIDMOD-LOOP 1
.SH NAME
vidmod-loop \- duplicate a video once into a loop
.SH SYNOPSIS
.B vidmod loop
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] \fIINPUT\fR [\fIOUTPUT\fR]
.SH DESCRIPTION
Create an output containing the input video twice in sequence.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-v, --version
Show the plugin name and version.
.SH SEE ALSO
.BR vidmod (1)
