.TH VIDMOD-MUTE 1
.SH NAME
vidmod-mute \- remove audio from a video
.SH SYNOPSIS
.B vidmod mute
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] \fIINPUT\fR [\fIOUTPUT\fR]
.SH DESCRIPTION
Remove the audio stream from a video while copying streams where possible.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
