.TH VIDMOD-LOOP 1
.SH NAME
vidmod-loop \- duplicate a video once into a loop
.SH SYNOPSIS
.B vidmod loop
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] [\fB-o\fR \fIOUTPUT\fR] \fIINPUT\fR
.SH DESCRIPTION
Create an output containing the input video twice in sequence.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-o \fIOUTPUT\fR
Write output to \fIOUTPUT\fR.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
