.TH VIDMOD-SLOWDOWN 1
.SH NAME
vidmod-slowdown \- slow down video and audio
.SH SYNOPSIS
.B vidmod slowdown
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] \fIINPUT\fR [\fIOUTPUT\fR]
.SH DESCRIPTION
Slow down the video and audio streams.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-v, --version
Show the plugin name and version.
.SH SEE ALSO
.BR vidmod (1)
