.TH VIDMOD-43 1
.SH NAME
vidmod-43 \- set video display aspect ratio to 4:3
.SH SYNOPSIS
.B vidmod 43
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] \fIINPUT\fR [\fIOUTPUT\fR]
.SH DESCRIPTION
Set the display aspect ratio of a video to 4:3.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
