.TH VIDMOD-CROSSFADE 1
.SH NAME
vidmod-crossfade \- create a video crossfade
.SH SYNOPSIS
.B vidmod crossfade
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] [\fB-o\fR \fIOUTPUT\fR] \fIINPUT\fR
.SH DESCRIPTION
Create a crossfade output with vidcrossfade.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Accepted for legacy command compatibility.
.TP
.B \-h
Show usage help.
.TP
.B \-o \fIOUTPUT\fR
Write output to \fIOUTPUT\fR.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
