.TH VIDMOD-MONO 1
.SH NAME
vidmod-mono \- convert audio to mono
.SH SYNOPSIS
.B vidmod mono
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] \fIINPUT\fR [\fIOUTPUT\fR]
.SH DESCRIPTION
Convert the video's audio stream to one channel.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-v, --version
Show the plugin name and version.
.SH SEE ALSO
.BR vidmod (1)
