.TH VIDMOD-MONO 1
.SH NAME
vidmod-mono \- convert audio to mono
.SH SYNOPSIS
.B vidmod mono
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] [\fB-o\fR \fIOUTPUT\fR] \fIINPUT\fR
.SH DESCRIPTION
Convert the video's audio stream to one channel.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-o \fIOUTPUT\fR
Write output to \fIOUTPUT\fR.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
