.TH VIDMOD-AUDIO 1
.SH NAME
vidmod-audio \- extract audio without video
.SH SYNOPSIS
.B vidmod audio
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] \fIINPUT\fR [\fIOUTPUT\fR]
.SH DESCRIPTION
Extract the input audio stream without video and copy the audio codec.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
