.TH VIDMOD-ROTATE90 1
.SH NAME
vidmod-rotate90 \- rotate video 90 degrees
.SH SYNOPSIS
.B vidmod rotate90
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] [\fB-o\fR \fIOUTPUT\fR] \fIINPUT\fR
.SH DESCRIPTION
Rotate the video image 90 degrees.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-o \fIOUTPUT\fR
Write output to \fIOUTPUT\fR.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
