.TH VIDMOD-MP4 1
.SH NAME
vidmod-mp4 \- convert video to MP4
.SH SYNOPSIS
.B vidmod mp4
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] [\fB-o\fR \fIOUTPUT\fR] \fIINPUT\fR
.SH DESCRIPTION
Convert the input video to an MP4 output.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-o \fIOUTPUT\fR
Write output to \fIOUTPUT\fR.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
