.TH VIDMOD-BUTTER 1
.SH NAME
vidmod-butter \- smooth video motion with butterflow
.SH SYNOPSIS
.B vidmod butter
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] [\fB-o\fR \fIOUTPUT\fR] \fIINPUT\fR
.SH DESCRIPTION
Use butterflow to create a smoother 120 fps video with audio.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Accepted for legacy command compatibility.
.TP
.B \-h
Show usage help.
.TP
.B \-o \fIOUTPUT\fR
Write output to \fIOUTPUT\fR.
.TP
.B \-v, --version
Show the plugin name and version.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH SEE ALSO
.BR vidmod (1)
