.TH VIDMOD 1
.SH NAME
vidmod \- video modification helpers
.SH SYNOPSIS
.B vidmod
<command> [<options>] [<args>]
.SH DESCRIPTION
Vidmod runs video modification command plugins.
.SH COMMANDS
Legacy vidmod 1 changes and additional video helpers are provided as bundled
plugins, including mp4, fit1080, twitter, rotate90, hevc, and the other
commands listed by
.BR "vidmod completion commands" .
