.TH VIDMOD-HEVC 1
.SH NAME
vidmod-hevc \- encode video as HEVC/H.265
.SH SYNOPSIS
.B vidmod hevc
[\fB-f\fR \fIFFMPEG-OPTIONS\fR] \fIINPUT\fR [\fIOUTPUT\fR]
.SH DESCRIPTION
Encode the video as HEVC/H.265 using libx265 and write an MP4 output.
.SH OPTIONS
.TP
.B \-f \fIFFMPEG-OPTIONS\fR
Pass extra ffmpeg options.
.TP
.B \-h
Show usage help.
.TP
.B \-v, --version
Show the plugin name and version.
.SH SEE ALSO
.BR vidmod (1)
