TOOL = vidmod
LIBEXEC_BINARIES = vidmod
LIBEXEC_FILES = vidmod lib plugins templates
MANPAGES = $(wildcard man/*.1)
BASH_COMPLETIONS = completions/bash/vidmod
ZSH_COMPLETIONS = completions/zsh/_vidmod
FISH_COMPLETIONS = completions/fish/vidmod.fish

include ../lib/install.mk
