.TH RMNLOGO 1 "August 2026" "rmnlogo 1.1.2" "User Commands"
.SH NAME
rmnlogo \- display the RÉMINO logo in the terminal
.SH SYNOPSIS
.B rmnlogo
.RI [ OPTION ] ...
.SH DESCRIPTION
.B rmnlogo
outputs the RÉMINO logo in ASCII art and ANSI colours.
.SH OPTIONS
.TP
.B -h
Show the help message.
.TP
.B -v
Show the program name and version.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 16
Invalid option or command-line arguments.
.SH EXAMPLES
.EX
rmnlogo
rmnlogo -v
.EE
.SH LICENSE
The
.B rmnlogo
source code is licensed under the ISC license.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
.SH ISSUES
GitHub: <https://github.com/remino/remutils>
.SH COPYRIGHT
Copyright \(co 2026 Rémino Rem.

The RÉMINO logo and artwork are copyrighted and are not covered by the
source-code license.

License ISC: <https://opensource.org/licenses/ISC>
.
