location = /remutils/addwatermark {
	return 301 /addwatermark/$is_args$args;
}

location /remutils/addwatermark/ {
	rewrite ^/remutils/addwatermark/(.*) /addwatermark/$1 permanent;
}

location = /remutils/cb2pdf {
	return 301 /cb2pdf/$is_args$args;
}

location /remutils/cb2pdf/ {
	rewrite ^/remutils/cb2pdf/(.*) /cb2pdf/$1 permanent;
}

location = /remutils/comprose {
	return 301 /comprose/$is_args$args;
}

location /remutils/comprose/ {
	rewrite ^/remutils/comprose/(.*) /comprose/$1 permanent;
}

location = /remutils/file2dataurl {
	return 301 /file2dataurl/$is_args$args;
}

location /remutils/file2dataurl/ {
	rewrite ^/remutils/file2dataurl/(.*) /file2dataurl/$1 permanent;
}

location = /remutils/genrand {
	return 301 /genrand/$is_args$args;
}

location /remutils/genrand/ {
	rewrite ^/remutils/genrand/(.*) /genrand/$1 permanent;
}

location = /remutils/imgmod {
	return 301 /imgmod/$is_args$args;
}

location /remutils/imgmod/ {
	rewrite ^/remutils/imgmod/(.*) /imgmod/$1 permanent;
}

location = /remutils/litesite {
	return 301 /litesite/$is_args$args;
}

location /remutils/litesite/ {
	rewrite ^/remutils/litesite/(.*) /litesite/$1 permanent;
}

location = /remutils/liverename {
	return 301 /liverename/$is_args$args;
}

location /remutils/liverename/ {
	rewrite ^/remutils/liverename/(.*) /liverename/$1 permanent;
}

location = /remutils/mkiso {
	return 301 /mkiso/$is_args$args;
}

location /remutils/mkiso/ {
	rewrite ^/remutils/mkiso/(.*) /mkiso/$1 permanent;
}

location = /remutils/mkprj {
	return 301 /mkprj/$is_args$args;
}

location /remutils/mkprj/ {
	rewrite ^/remutils/mkprj/(.*) /mkprj/$1 permanent;
}

location = /remutils/mkwebalbum {
	return 301 /mkwebalbum/$is_args$args;
}

location /remutils/mkwebalbum/ {
	rewrite ^/remutils/mkwebalbum/(.*) /mkwebalbum/$1 permanent;
}

location = /remutils/mkx {
	return 301 /mkx/$is_args$args;
}

location /remutils/mkx/ {
	rewrite ^/remutils/mkx/(.*) /mkx/$1 permanent;
}

location = /remutils/osc52 {
	return 301 /osc52/$is_args$args;
}

location /remutils/osc52/ {
	rewrite ^/remutils/osc52/(.*) /osc52/$1 permanent;
}

location = /remutils/rmnlogo {
	return 301 /rmnlogo/$is_args$args;
}

location /remutils/rmnlogo/ {
	rewrite ^/remutils/rmnlogo/(.*) /rmnlogo/$1 permanent;
}

location = /remutils/rrrr {
	return 301 /rrrr/$is_args$args;
}

location /remutils/rrrr/ {
	rewrite ^/remutils/rrrr/(.*) /rrrr/$1 permanent;
}

location = /remutils/rsdeploy {
	return 301 /rsdeploy/$is_args$args;
}

location /remutils/rsdeploy/ {
	rewrite ^/remutils/rsdeploy/(.*) /rsdeploy/$1 permanent;
}

location = /remutils/timinal {
	return 301 /timinal/$is_args$args;
}

location /remutils/timinal/ {
	rewrite ^/remutils/timinal/(.*) /timinal/$1 permanent;
}

location = /remutils/urlshortcut {
	return 301 /urlshortcut/$is_args$args;
}

location /remutils/urlshortcut/ {
	rewrite ^/remutils/urlshortcut/(.*) /urlshortcut/$1 permanent;
}

location = /remutils/vid2gif {
	return 301 /vid2gif/$is_args$args;
}

location /remutils/vid2gif/ {
	rewrite ^/remutils/vid2gif/(.*) /vid2gif/$1 permanent;
}

location = /remutils/vidmod {
	return 301 /vidmod/$is_args$args;
}

location /remutils/vidmod/ {
	rewrite ^/remutils/vidmod/(.*) /vidmod/$1 permanent;
}

location = /remutils/waituntil {
	return 301 /waituntil/$is_args$args;
}

location /remutils/waituntil/ {
	rewrite ^/remutils/waituntil/(.*) /waituntil/$1 permanent;
}

location = /remutils/webshot {
	return 301 /webshot/$is_args$args;
}

location /remutils/webshot/ {
	rewrite ^/remutils/webshot/(.*) /webshot/$1 permanent;
}

