#!/usr/bin/env bash

VERSION=1.0.0

_usage() {
	echo "USAGE: $(basename "$0") [-v] <input_dir> <output.iso>"
}

mkiso_main() {
	# export PS4='+ ${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]}() '
	# set -x
	set -euo pipefail

	E_ARGS=16
	E_MISSING_FILE=17
	E_MISSING_APP=18

	[ $# -eq 0 ] && _usage && return
	[ $1 == "-v" ] && echo "$(basename "$0") $VERSION" && return
	[ $# -lt 2 ] && _fatal $E_ARGS "Missing arguments."

	_require hdiutil

	DIR="$1"
	ISO="$2"

	[ ! -d "$DIR" ] && _fatal $E_MISSING_FILE "Missing or not a directory: $DIR"

	hdiutil makehybrid -iso -joliet -ov -o "$ISO" "$DIR"
}

_fatal() {
	local exit_code=$1
	shift
	echo "FATAL: $*" >&2
	exit "$exit_code"
}

_require() {
	missing_bin=0

	for bin in "$@"; do
		if ! which "$bin" >/dev/null 2>&1; then
			missing_bin=1
			_error "Required: $bin"
		fi
	done

	if [ $missing_bin -ne 0 ]; then
		_fatal "$E_MISSING_APP" "One or more executables or apps are missing."
	fi
}

mkiso_main "$@"
