.TH IMGMOD-CHAIN 1
.SH NAME
imgmod-chain \- run multiple imgmod plugins in sequence
.SH SYNOPSIS
.B imgmod chain
<command> [options] -- <command> [options] -- <input> <output>
.SH DESCRIPTION
Run two or more chainable imgmod plugins, passing temporary output from each
stage to the next stage.
.SH AUTHOR
Written by Rémino Rem: <https://remino.net/>
